/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemeRouteImport } from './routes/theme'
import { Route as SoumissionRouteImport } from './routes/soumission'
import { Route as LieuRouteImport } from './routes/lieu'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComitesRouteImport } from './routes/comites'
import { Route as AxesRouteImport } from './routes/axes'
import { Route as IndexRouteImport } from './routes/index'

const ThemeRoute = ThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const SoumissionRoute = SoumissionRouteImport.update({
  id: '/soumission',
  path: '/soumission',
  getParentRoute: () => rootRouteImport,
} as any)
const LieuRoute = LieuRouteImport.update({
  id: '/lieu',
  path: '/lieu',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComitesRoute = ComitesRouteImport.update({
  id: '/comites',
  path: '/comites',
  getParentRoute: () => rootRouteImport,
} as any)
const AxesRoute = AxesRouteImport.update({
  id: '/axes',
  path: '/axes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/axes': typeof AxesRoute
  '/comites': typeof ComitesRoute
  '/contact': typeof ContactRoute
  '/inscription': typeof InscriptionRoute
  '/lieu': typeof LieuRoute
  '/soumission': typeof SoumissionRoute
  '/theme': typeof ThemeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/axes': typeof AxesRoute
  '/comites': typeof ComitesRoute
  '/contact': typeof ContactRoute
  '/inscription': typeof InscriptionRoute
  '/lieu': typeof LieuRoute
  '/soumission': typeof SoumissionRoute
  '/theme': typeof ThemeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/axes': typeof AxesRoute
  '/comites': typeof ComitesRoute
  '/contact': typeof ContactRoute
  '/inscription': typeof InscriptionRoute
  '/lieu': typeof LieuRoute
  '/soumission': typeof SoumissionRoute
  '/theme': typeof ThemeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/axes'
    | '/comites'
    | '/contact'
    | '/inscription'
    | '/lieu'
    | '/soumission'
    | '/theme'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/axes'
    | '/comites'
    | '/contact'
    | '/inscription'
    | '/lieu'
    | '/soumission'
    | '/theme'
  id:
    | '__root__'
    | '/'
    | '/axes'
    | '/comites'
    | '/contact'
    | '/inscription'
    | '/lieu'
    | '/soumission'
    | '/theme'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AxesRoute: typeof AxesRoute
  ComitesRoute: typeof ComitesRoute
  ContactRoute: typeof ContactRoute
  InscriptionRoute: typeof InscriptionRoute
  LieuRoute: typeof LieuRoute
  SoumissionRoute: typeof SoumissionRoute
  ThemeRoute: typeof ThemeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soumission': {
      id: '/soumission'
      path: '/soumission'
      fullPath: '/soumission'
      preLoaderRoute: typeof SoumissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lieu': {
      id: '/lieu'
      path: '/lieu'
      fullPath: '/lieu'
      preLoaderRoute: typeof LieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comites': {
      id: '/comites'
      path: '/comites'
      fullPath: '/comites'
      preLoaderRoute: typeof ComitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/axes': {
      id: '/axes'
      path: '/axes'
      fullPath: '/axes'
      preLoaderRoute: typeof AxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AxesRoute: AxesRoute,
  ComitesRoute: ComitesRoute,
  ContactRoute: ContactRoute,
  InscriptionRoute: InscriptionRoute,
  LieuRoute: LieuRoute,
  SoumissionRoute: SoumissionRoute,
  ThemeRoute: ThemeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
